package com.fingerdance.ssc.attacks

enum class AttackMod {
    XMOD,
    BOOST, BRAKE, WAVE, EXPAND, BOOMERANG,
    DRUNK, DIZZY, CONFUSION, TORNADO, TIPSY, BUMPY, BEAT,
    TWIRL, ROLL,
    BIG ,MINI, TINY,
    OVERHEAD, HALLWAY, DISTANT, INCOMING, SPACE,
    REVERSE, SPLIT, ALTERNATE, CROSS, CENTERED, FLIP, INVERT,
    DARK, STEALTH, HIDDEN, SUDDEN, BLINK, RANDOM_VANISH, BLIND,
    EARTHWORM,

    MOVE_Z,

    NORMAL, UNKNOWN
}
